name: daskalou test site
favicon: null
layout_spectrum: 1
typography_spectrum: 0.94324
title: Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#069ea2'
    - '#000000'
    - '#00ffff'
    - '#0000ff'
    - '#005555'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
