name: daskalou test site
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34571
title: Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7a7a0'
    - '#000000'
    - '#d7cfc9'
    - '#79625a'
    - '#46332d'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
