name: daskalou test site
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40568
title: Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e7d3'
    - '#44494c'
    - '#696c63'
    - '#000100'
    - '#201f1d'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
