name: daskalou test site
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34571
title: Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ce000c'
    - '#fee519'
    - '#130000'
    - '#fffdff'
    - '#b0a633'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
